# sum_action/action.yml

name: "Sum Action"
description: "Calculate the sum of two environment variables"
inputs:
  VAL_A:
    description: "First integer value"
    required: true
  VAL_B:
    description: "Second integer value"
    required: true
  NUMBERS_FILE:
    description: "Path to the numbers.yaml file"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.VAL_A }}
    - ${{ inputs.VAL_B }}
    - ${{ inputs.NUMBERS_FILE }}

