# action.yaml
name: 'Register data product'
description: 'A GitHub Action that takes a data product yaml specification as input and registers the data product on the data product registry'
author: Anil Nair
inputs:
  environment:
    description: "Environment to deploy to"
    type: environment
    required: true
    default: prod

outputs:
  num_squared:
    description: 'Square of the input'
    value: ${{ steps.get-square.outputs.num_squared }}
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  
    - name: Install Dependencies
      run: pip install -r actions/dp_registry/requirements.txt
      shell: bash
    - name: run python file
      id: dp-registry
      run: python actions/dp_registry/src/register.py
      shell: bash
      env:
        CLIENT_ID: ${{ inputs.client_id }}
        CLIENT_SECRET: ${{ inputs.client_secret }}