# action.yaml
name: 'Register data product'
description: 'A GitHub Action that takes a data product yaml specification as input and registers the data product on the data product registry'
author: Anil Nair
inputs:
  environment:
    description: "Environment to deploy to"
    type: environment
    required: true
    default: prod

  num:
    description: 'Enter a number'
    required: true
    default: "1"
outputs:
  num_squared:
    description: 'Square of the input'
    value: ${{ steps.get-square.outputs.num_squared }}
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  
    - name: Install Dependencies
      run: pip install -r actions/register/requirements.txt
      shell: bash
    - name: Pass Inputs to Shell
      run: |
              echo "INPUT_NUM=${{ inputs.num }}" >> $GITHUB_ENV
      shell: bash
    - name: Fetch the number's square
      id: get-square
      run: python actions/register/src/register.py
      shell: bash
