# .github/workflows/dp_registry.yaml
name: Register Data Product

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "prod"
        type: environment


jobs:
  get-num-square:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    name: Register a data product
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: register data product
        id: dp_registry
        uses: ./actions/dp_registry
        with:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      - name: Print the output
        run: echo "${{ steps.dp_registry.outputs.num_squared }}"
