# .github/workflows/register_dp.yaml
name: Register Data Product

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "prod"
        type: environment


jobs:
  get-num-square:
    runs-on: ubuntu-latest
    name: Returns the number square
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch num squared
        id: get_square
        uses: ./actions/dp_registry # Uses an action in the register directory
        # or use a released GitHub Action
        # uses: shipyard/github-action/fetch-shipyard-env@1.0.0
        with:
          client_id: ${{ secrets.ENTRA_CLIENT_ID }}
          client_secret: ${{ secrets.ENTRA_CLIENT_SECRET }}
      - name: Print the square
        run: echo "${{ steps.get_square.outputs.num_squared }}"
