# .github/workflows/register_dp.yaml
name: num squared

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "prod"
        type: environment


jobs:
  get-num-square:
    runs-on: ubuntu-latest
    name: Returns the number square
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch num squared
        id: get_squared
        uses: ./actions/get_squared 
        with:
          num: 11
      - name: Print the square
        run: echo "${{ steps.get_squared.outputs.num_squared }}"
