# .github/workflows/sum_calculation.yml
name: Calculate Sum

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "prod"
        type: environment

jobs:
  calculate_sum:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get template
      id: get_template
      run: |
        echo "yaml_content=$(cat ./template/numbers.yaml)" >> $GITHUB_ENV
    
    - name: Use Sum Action
      uses: ./actions/sum_action
      with:
        VAL_A: ${{ secrets.VAL_A }}
        VAL_B: ${{ secrets.VAL_B }}
        NUMBERS_FILE: ${{ env.yaml_content }}
