# .github/workflows/sum_calculation.yml

name: Calculate Sum

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "prod"
        type: environment

jobs:
  calculate_sum:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: python -m pip install --upgrade pip
    
    - name: Calculate Sum
      env:
        VAL_A: ${{ secrets.VAL_A }}
        VAL_B: ${{ secrets.VAL_B }}
      run: python calculate_sum.py

